import Head from 'next/head'
import Link from 'next/link'

import { DefaultCard as Card } from '@components/Card'
import { BottomMenu } from '@components/Footer'
import { Container } from '@components/Layout'
import { Search } from '@components/Forms'

const Recipes = () => {
  return (
    <div>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-6">
        <Container>
          <div className="pt-4 pb-20">
            <Search />
            <div className="grid grid-cols-2 gap-3 mt-6">
              {[...Array(6)].map(() => (
                <div key={Math.random()}>
                  <Link href="/recipes/slug" passHref>
                    <a>
                      <Card />
                    </a>
                  </Link>
                </div>
              ))}
            </div>
          </div>
        </Container>
        <BottomMenu />
      </main>
    </div>
  )
}

export default Recipes
