import Head from "next/head";
import styles from "@styles/Home.module.css";
import { Search } from "@components/Forms";
import { Container } from "@components/Layout";
import { BottomMenu } from "@components/Footer";

const Recipes = () => {
  return (
    <div>
      <Head>
        <title>Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-6">
        <Container>
          <Search />
        </Container>
        <BottomMenu />
      </main>
    </div>
  );
};

export default Recipes;
