import Head from 'next/head'
import { Container } from '@components/Layout'
import Image from 'next/image'
import Link from 'next/link'

const RecipeDetail = () => {
  return (
    <div>
      <Head>
        <title>Recipe Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-6 pb-12">
        <Container>
          <Link href="/recipes" passHref>
            <a>
              <div className="flex space-x-4">
                <div>
                  <Image src="/static/icons/arrow-left-icon.svg" layout="fixed" height={25} width={25} alt="" />
                </div>{' '}
                <span className="-mt-0.5 text-xl">Kembali</span>{' '}
              </div>
            </a>
          </Link>
          <div className="flex flex-col space-y-4">
            <div className="relative w-full h-[13rem] mt-6">
              <Image
                src="/static/images/example-food-image.jpg"
                layout="fill"
                className="object-cover object-center"
                alt=""
              />
            </div>
            <h1 className="text-2xl font-bold">Vegetable With Sosis Wenak by Sumedang Food</h1>
            <p>
              Masakan ini merupakan masakan sehat dengan bahan - bahan yang sehat bagi tubuh karena banyak menggunakan
              sayuran
            </p>
            <div>
              <h2 className="text-lg font-semibold">Bahan :</h2>
              <ol className="pl-5 list-disc">
                <li>1 Bungkus Sosis</li>
                <li>1kg terigu</li>
                <li>5 lembar selada</li>
                <li>1 sachet saus tiram</li>
              </ol>
            </div>
            <div>
              <h2 className="text-lg font-semibold">Rekomendasi Alat :</h2>
              <ol className="pl-5 list-disc">
                <li>Pisau</li>
                <li>Kompor</li>
                <li>Wajan</li>
              </ol>
            </div>
            <div>
              <h2 className="text-lg font-semibold">Langkah - langkah :</h2>
              <ol className="pl-5 list-decimal">
                <li>Potong sosis</li>
                <li>Buat adonan terigu</li>
                <li>Iris Sayuran</li>
                <li>Masukan sayuran dan sosis ke adonan terigu</li>
                <li>Panaskan minyak</li>
                <li className="flex space-x-2">
                  <span>Goreng selama 3 menit</span>{' '}
                  <span className="flex items-center">
                    <Image src="/static/icons/timer-icon.svg" layout="fixed" height={20} width={20} alt="" />
                  </span>
                </li>
              </ol>
            </div>
          </div>

          <div className="flex justify-center mt-12">
            <Link href="/cooking-step/slug" passHref>
              <a>
                <button className="px-5 py-3 text-white bg-blue-600 rounded-md">Mulai Memasak</button>
              </a>
            </Link>
          </div>
        </Container>
      </main>
    </div>
  )
}

export default RecipeDetail
