import Head from 'next/head'
import { useState, useEffect } from 'react'
import { fetcher } from '@services/fetcher'
import { Container } from '@components/Layout'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft, Timer } from '@components/Icons'

const RecipeDetail = ({ slug }) => {
  const [recipe, setRecipe] = useState({})

  const getRecipe = () => {
    fetcher(process.env.API_URL + '/recipes/' + slug + '?populate=deep').then((data) => setRecipe(data?.data))
  }

  console.log(recipe)
  useEffect(() => {
    getRecipe()
    return
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  return (
    <div>
      <Head>
        <title>Recipe Detail</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="pt-6 pb-12">
        <Container>
          <Link href="/recipes" passHref>
            <a>
              <div className="flex space-x-4">
                <div>
                  <ArrowLeft />
                </div>{' '}
                <span className="-mt-0.5 text-xl">Kembali</span>{' '}
              </div>
            </a>
          </Link>
          <div className="flex flex-col space-y-4">
            <div className="relative w-full h-[13rem] mt-6">
              {/* to do make default image when image is null */}
              <Image
                src={`${
                  recipe?.attributes?.thumbnail?.data?.attributes?.url
                    ? recipe?.attributes?.thumbnail?.data?.attributes?.url
                    : '/static/images/default-image-not-found.png'
                }`}
                layout="fill"
                className="object-cover object-center"
                alt=""
              />
            </div>
            <h1 className="text-2xl font-bold">{recipe?.attributes?.title}</h1>
            <p>{recipe?.attributes?.description}</p>
            <div>
              <h2 className="text-lg font-semibold">Bahan :</h2>
              <ol className="pl-5 list-disc">
                {recipe?.attributes?.ingredients.map((ingredient) => (
                  <li key={Math.random()}>{ingredient?.title}</li>
                ))}
              </ol>
            </div>
            <div>
              <h2 className="text-lg font-semibold">Rekomendasi Alat :</h2>
              <ol className="pl-5 list-disc">
                <li>Pisau</li>
                <li>Kompor</li>
                <li>Wajan</li>
              </ol>
            </div>
            <div>
              <h2 className="text-lg font-semibold">Langkah - langkah :</h2>
              <ol className="pl-5 list-decimal">
                {recipe?.attributes?.steps.map((step) => (
                  <li key={Math.random()}>
                    <span className="mr-4">{step?.description}</span>
                    {step?.timer > 0 && (
                      <span className="flex items-center">
                        <Timer />
                      </span>
                    )}
                  </li>
                ))}
              </ol>
            </div>
          </div>

          <div className="flex justify-center mt-12">
            <Link href={`/cooking-step/${recipe?.attributes?.slug}`} passHref>
              <a>
                <button className="px-5 py-3 text-white bg-blue-600 rounded-md">Mulai Memasak</button>
              </a>
            </Link>
          </div>
        </Container>
      </main>
    </div>
  )
}

export const getServerSideProps = async (ctx) => {
  const query = ctx.query

  return {
    props: {
      slug: query?.slug
    }
  }
}

export default RecipeDetail
