import Head from "next/head";
import styles from "@styles/Home.module.css";
import { fetcher } from "@services/fetcher";
export default function Home() {
  const hitAPI = fetcher("https://jsonplaceholder.typicode.com/todos").then(
    (data) => console.log(data)
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
      </main>
    </div>
  );
}
