import Head from "next/head";
import styles from "@styles/Home.module.css";
import { fetcher } from "@services/fetcher";
import { Search } from "@components/Forms";

const HomePage = () => {
  const hitAPI = fetcher("https://jsonplaceholder.typicode.com/todos").then(
    (data) => console.log(data)
  );
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-center font-bold mb-4">Marasak</h1>
        <Search />
      </main>
    </div>
  );
};

export default HomePage;
