import Head from "next/head";
import styles from "@styles/Home.module.css";
import { fetcher } from "@services/fetcher";
import { Search } from "@components/Forms";
import { Container } from "@components/Layout";
import { BottomMenu } from "@components/Footer";

const HomePage = () => {
  const hitAPI = fetcher("https://jsonplaceholder.typicode.com/todos").then(
    (data) => console.log(data)
  );
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <h1 className="mb-4 font-bold text-center">Logo</h1>
          <Search />
        </Container>
        <BottomMenu />
      </main>
    </div>
  );
};

export default HomePage;
