import Head from 'next/head'
import { useState, useEffect } from 'react'
import { fetcher } from '@services/fetcher'
import { Search } from '@components/Forms'
import { Container } from '@components/Layout'
// import { BottomMenu } from '@components/Footer'
import { DefaultCard as Card } from '@components/Card'
import Link from 'next/link'
import { Header } from '@components/Header'

const HomePage = () => {
  const [recipes, setRecipes] = useState([])
  const [isLoading, setIsLoading] = useState(false)

  const getRecipes = () => {
    setIsLoading(true)
    fetcher(process.env.API_URL + '/recipes?populate=*')
      .then((data) => setRecipes(data?.data))
      .then(() => setIsLoading(false))
  }

  useEffect(() => {
    getRecipes()
    return
  }, [])
  return (
    <div>
      <Head>
        <title>Marasak</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="mt-4">
            <Header />
          </div>
          <div className="pt-10 pb-20">
            <Search onSearch={(e) => setRecipes(e)} />
            {isLoading ? (
              <h1 className="mt-4 text-center">Mengambil Data..</h1>
            ) : (
              <div className="grid grid-cols-2 gap-3 mt-6 ">
                {recipes.map((recipe) => (
                  <div key={Math.random()}>
                    <Link href={`/recipes/${recipe?.attributes?.slug}`} passHref>
                      <a>
                        <Card
                          url_image={recipe?.attributes?.thumbnail?.data?.attributes.url}
                          type={recipe?.attributes?.type}
                          title={recipe?.attributes?.title}
                          lessIngredient={recipe?.attributes?.lessIngredient}
                          cookingTime={recipe?.attributes?.cookingTime}
                        />
                      </a>
                    </Link>
                  </div>
                ))}
              </div>
            )}
          </div>
        </Container>
        {/* <BottomMenu /> */}
      </main>
    </div>
  )
}

export default HomePage
